name: checks

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
      - develop

permissions:
  contents: read
  issues: write
  pull-requests: write

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: ringo-test/github-actions-common/.github/actions/change-file@main
      - uses: ringo-test/github-actions-common/.github/actions/lint@main
        with:
          config-file: ""

  validate-assets:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: ringo-test/github-actions-common/.github/actions/change-file@main
      - uses: ringo-test/github-actions-common/.github/actions/validate-assets@main
        with:
          max-image-size-mb: 5
          max-image-dimension: 2048
          require-meta: true

  detect-vietnamese:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: ringo-test/github-actions-common/.github/actions/change-file@main
      - uses: ringo-test/github-actions-common/.github/actions/detect-vietnamese@main
        with:
          exclude: ""
          scan-scene: false
          scan-prefab: false
