name: checks

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
      - develop

permissions:
  contents: read
  issues: write
  pull-requests: write

jobs:
  checks:
    uses: ringo-test/github-actions-commo/.github/workflows/checks.yml@main
    with:
      action-repo: 'ringo-test/github-actions-commo'
      eslint-config-file: ""
      max-image-size-mb: 5
      max-image-dimension: 2048
      require-meta: true
      detect-vietnamese-exclude: ""
      detect-vietnamese-scan-scene: false
      detect-vietnamese-scan-prefab: false
