name: pr

on:
  workflow_dispatch:
  pull_request:
    types:
      - opened
      - edited
      - reopened
  push:
    branches:
      - main
      - develop

permissions:
  contents: read
  issues: write
  pull-requests: write

jobs:
  pr:
    uses: ringo-test/github-actions-common/.github/workflows/pr.yml@main
    with:
      action-repo: 'ringo-test/github-actions-common'
      branch-prefixes: feature,fix,refactor,chore,hotfix,test,docs
      pr-prefixes: feature,fix,refactor,hotfix,docs
